version: '3'

services:
  flask_app:
    build: .
    container_name: flask_app
    environment:
      - DB_URL=mongodb://root:pass@mongo_db:27017
      - DB_NAME=forms
    command: python -m app.main
    ports:
      - 5000:5000
    depends_on:
      - mongo_db
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=forms
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass